# ═══════════════════════════════════════════════════════════════════════════════
# SDOF Elastic Spring System — Static Analysis
# Generated by Multi-Agent System (7-Agent Pipeline)
# Unit system: kN, m, s
# ═══════════════════════════════════════════════════════════════════════════════

import openseespy.opensees as ops
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os



# ─── Clean slate ───────────────────────────────────────────
ops.wipe()

# ─── Model: 1D, 1 DOF per node ────────────────────────────
ops.model('basic', '-ndm', 1, '-ndf', 1)

# ─── Nodes (both at x = 0, since zeroLength) ──────────────
ops.node(1, 0.0)  # fixed node
ops.node(2, 0.0)  # free node

# ─── Boundary: fix node 1 ─────────────────────────────────
ops.fix(1, 1)

# ─── Material: elastic, tag=1 ─────────────────────────────
k = 20000.0  # N/m
ops.uniaxialMaterial('Elastic', 1, k)

# ─── Element: zeroLength spring ────────────────────────────
#   element zeroLength tag iNode jNode -mat matTag -dir dofDir
ops.element('zeroLength', 1, 1, 2, '-mat', 1, '-dir', 1)

# ─── Load ──────────────────────────────────────────────────
F_total = 10000.0  # N
num_steps = 5

ops.timeSeries('Linear', 1)
ops.pattern('Plain', 1, 1)
ops.load(2, F_total)  # full load on node 2, scaled by load factor

# ─── Analysis settings ─────────────────────────────────────
ops.system('BandGeneral')
ops.numberer('Plain')
ops.constraints('Plain')
ops.integrator('LoadControl', 1.0 / num_steps)  # each step = 1/5 of total
ops.algorithm('Linear')
ops.analysis('Static')

# ─── Run & record ──────────────────────────────────────────
displacements = [0.0]
forces = [0.0]

for step in range(1, num_steps + 1):
    ok = ops.analyze(1)
    if ok != 0:
        print(f"Analysis failed at step {step}")
        break

    d = ops.nodeDisp(2, 1)
    f = step * (F_total / num_steps)
    displacements.append(d)
    forces.append(f)

    print(f"Step {step}: load = {f:>8.1f} N,  disp = {d:.4f} m")

print(f"\nFinal displacement: {displacements[-1]:.4f} m")
print(f"Expected (F/k):    {F_total / k:.4f} m")

# ─── Plot: force-displacement curve ────────────────────────
fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(displacements, forces, 'o-', color='#2563eb', linewidth=2, markersize=8)
ax.set_xlabel('Displacement (m)', fontsize=12)
ax.set_ylabel('Force (N)', fontsize=12)
ax.set_title('SDOF Static Analysis — Force vs Displacement', fontsize=14)
ax.grid(True, alpha=0.3)
ax.set_xlim(left=0)
ax.set_ylim(bottom=0)

# Annotate final point
ax.annotate(f'({displacements[-1]:.2f} m, {forces[-1]:.0f} N)',
            xy=(displacements[-1], forces[-1]),
            xytext=(-80, 15), textcoords='offset points',
            fontsize=10, arrowprops=dict(arrowstyle='->', color='gray'))

plt.tight_layout()
plt.savefig('force_displacement.png', dpi=150)
print("\nSaved: force_displacement.png")
plt.show()

ops.wipe()
