# ═══════════════════════════════════════════════════════════════════════════════
# 单层单跨钢框架非线性Pushover分析
# Single-Story Single-Bay Steel Frame Nonlinear Pushover Analysis
# Generated by Multi-Agent System (7+3 Architecture)
# ═══════════════════════════════════════════════════════════════════════════════
#
# Unit system: kN, m, s (stresses in kPa = MPa x 1000)
#
# Structure:
#   Node 3 ────── Node 5 ────── Node 4     y = 3.6 m
#     |           (mid)           |
#     |           x=3.0           |
#     |                           |
#   Node 1                     Node 2      y = 0.0 m
#   x=0.0 (Fixed)             x=6.0 (Fixed)
#
# Columns: 300x300 mm solid steel, dispBeamColumn, PDelta
# Beam:    300x400 mm solid steel, dispBeamColumn, Linear
# Material: Steel01, fy=345 MPa, E=206 GPa, b=0.01
# ═══════════════════════════════════════════════════════════════════════════════

import openseespy.opensees as ops
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os

# =============================================================================
# Section 1: Model Initialization  [Modeling Agent]
# =============================================================================
ops.wipe()
ops.model('basic', '-ndm', 2, '-ndf', 3)

# --- Geometry Parameters ---
SPAN = 6.0    # m, bay width
H    = 3.6    # m, story height
HMID = SPAN / 2.0  # 3.0 m, mid-span x-coordinate

# --- Node Layout ---
#
#  Node 3 (0, 3.6) ---- Node 5 (3, 3.6) ---- Node 4 (6, 3.6)   <- Roof
#      |                                           |
#      |  Left column (Elem 1)     Right column (Elem 2)
#      |                                           |
#  Node 1 (0, 0)                           Node 2 (6, 0)         <- Base (FIXED)
#
# Beam split at mid-span:
#   Elem 3: Node 3 -> Node 5 (left half)
#   Elem 4: Node 5 -> Node 4 (right half)

# --- Nodes ---
ops.node(1, 0.0,  0.0)        # Base, left column
ops.node(2, SPAN, 0.0)        # Base, right column
ops.node(3, 0.0,  H)          # Roof, left column top
ops.node(4, SPAN, H)          # Roof, right column top
ops.node(5, HMID, H)          # Roof, beam mid-span (deflection control)

# --- Boundary Conditions ---
ops.fix(1, 1, 1, 1)           # Left base: fully fixed
ops.fix(2, 1, 1, 1)           # Right base: fully fixed

# =============================================================================
# Section 2: Material & Sections  [Material Agent]
# =============================================================================

# --- Material: Steel01 (tag=1) ---
# fy = 345 MPa = 345.0e3 kPa, E0 = 206 GPa = 206.0e6 kPa, b = 0.01
ops.uniaxialMaterial('Steel01', 1, 345.0e3, 206.0e6, 0.01)

# --- Column Fiber Section (tag=101): 300mm x 300mm ---
# y in [-0.15, 0.15] (depth, vertical), z in [-0.15, 0.15] (width, horizontal)
ops.section('Fiber', 101, '-GJ', 1.0e10)
ops.patch('rect', 1, 10, 10, -0.15, -0.15, 0.15, 0.15)

# --- Beam Fiber Section (tag=102): 300mm x 400mm ---
# y in [-0.20, 0.20] (depth=400mm, vertical), z in [-0.15, 0.15] (width=300mm, horizontal)
ops.section('Fiber', 102, '-GJ', 1.0e10)
ops.patch('rect', 1, 10, 10, -0.20, -0.15, 0.20, 0.15)

# --- Beam Integrations (Lobatto) ---
ops.beamIntegration('Lobatto', 1, 101, 5)  # column: tag=1, secTag=101, 5 points
ops.beamIntegration('Lobatto', 2, 102, 5)  # beam:   tag=2, secTag=102, 5 points

# =============================================================================
# Section 3: Nodes, Elements, BCs  [Modeling Agent]
# =============================================================================

# --- Geometric Transformations (MUST precede element definitions) ---
ops.geomTransf('PDelta', 1)   # Tag 1: PDelta for columns
ops.geomTransf('Linear', 2)   # Tag 2: Linear for beams

# --- Elements ---
# dispBeamColumn(eleTag, iNode, jNode, transfTag, integrationTag)
ops.element('dispBeamColumn', 1, 1, 3, 1, 1)   # Left column  (PDelta, integ 1)
ops.element('dispBeamColumn', 2, 2, 4, 1, 1)   # Right column (PDelta, integ 1)
ops.element('dispBeamColumn', 3, 3, 5, 2, 2)   # Beam left half  (Linear, integ 2)
ops.element('dispBeamColumn', 4, 5, 4, 2, 2)   # Beam right half (Linear, integ 2)

# =============================================================================
# Section 4: Recorders  [PostProcessing Agent - Part A]
# =============================================================================

os.makedirs('output', exist_ok=True)

# Recorder 1: Top lateral displacement at Node 3 (control node for lateral drift)
SUPPORT_NODES = [1, 2]  # Extracted from Modeling Summary BCs table
ops.recorder('Node', '-file', 'output/top_disp.txt', '-time',
             '-node', 3, '-dof', 1, 'disp')

# Recorder 2: Beam mid-span vertical deflection at Node 5
ops.recorder('Node', '-file', 'output/midspan_disp.txt', '-time',
             '-node', 5, '-dof', 2, 'disp')

# Recorder 3: Support reactions at fixed base nodes [1, 2]
ops.recorder('Node', '-file', 'output/reactions.txt', '-time',
             '-node', *SUPPORT_NODES, '-dof', 1, 2, 3, 'reaction')

# Recorder 4: Fiber stress-strain at left column base (Element 1, section 1)
ops.recorder('Element', '-file', 'output/fiber_stress.txt', '-time',
             '-ele', 1, 'section', 1, 'fiber', -0.15, 0.0, 'stressStrain')

# =============================================================================
# Section 5: Loading & Analysis  [Analysis Agent]
# =============================================================================

# --- Stage 1: Gravity Analysis ---
print("=" * 60)
print("Stage 1: Gravity Analysis")
print("=" * 60)

ops.timeSeries('Linear', 1)
ops.pattern('Plain', 1, 1)
ops.eleLoad('-ele', 3, 4, '-type', '-beamUniform', -10.0)

ops.constraints('Plain')
ops.numberer('RCM')
ops.system('BandGeneral')
ops.test('NormUnbalance', 1.0e-6, 25)
ops.algorithm('Newton')
ops.integrator('LoadControl', 0.1)
ops.analysis('Static')

gravity_ok = True
for i in range(10):
    ok = ops.analyze(1)
    if ok != 0:
        print("[FAIL] Gravity step " + str(i + 1) + " failed to converge.")
        gravity_ok = False
        break
    if (i + 1) % 5 == 0:
        print("  Gravity step " + str(i + 1) + "/10 [OK]")

if gravity_ok:
    print("[OK] Gravity analysis complete. Load factor = 1.0")
else:
    print("[FAIL] Gravity analysis did not complete.")

# Freeze gravity loads and reset pseudo-time
ops.loadConst('-time', 0.0)
print("  Gravity loads frozen. Pseudo-time reset to 0.0.")

# --- Stage 2: Lateral Pushover Analysis (Displacement Control) ---
print("")
print("=" * 60)
print("Stage 2: Lateral Pushover (Displacement Control)")
print("=" * 60)

ops.timeSeries('Linear', 2)
ops.pattern('Plain', 2, 2)
ops.load(3, 1.0, 0.0, 0.0)   # Unit reference load at Node 3, X direction

# Target: H/50 = 3.6/50 = 0.072 m = 72 mm (well into yielding)
target_disp = 0.072   # m
n_pushover_steps = 360
d_step = target_disp / n_pushover_steps  # 0.0002 m per step

ops.constraints('Plain')
ops.numberer('RCM')
ops.system('BandGeneral')
ops.test('NormDispIncr', 1.0e-8, 50)
ops.algorithm('Newton')
ops.integrator('DisplacementControl', 3, 1, d_step)  # Node 3, DOF 1
ops.analysis('Static')

pushover_ok = True
disp_history = []
force_history = []

for i in range(n_pushover_steps):
    ok = ops.analyze(1)

    if ok != 0:
        ops.algorithm('KrylovNewton')
        ok = ops.analyze(1)

    if ok != 0:
        ops.algorithm('ModifiedNewton')
        ops.test('NormDispIncr', 1.0e-6, 200)
        ok = ops.analyze(1)

    if ok != 0:
        ops.algorithm('BFGS')
        ok = ops.analyze(1)

    if ok != 0:
        ops.algorithm('NewtonLineSearch', '-type', 'Bisection')
        ok = ops.analyze(1)

    ops.algorithm('Newton')
    ops.test('NormDispIncr', 1.0e-8, 50)

    if ok != 0:
        print("[FAIL] Pushover step " + str(i + 1) + " failed after all fallbacks.")
        pushover_ok = False
        break

    # Record load-displacement at each step
    curr_disp = ops.nodeDisp(3, 1)
    ops.reactions()
    base_shear = ops.nodeReaction(1, 1) + ops.nodeReaction(2, 1)
    disp_history.append(curr_disp * 1000.0)   # m -> mm
    force_history.append(-base_shear)          # Negate: reaction opposes applied

    if (i + 1) % 60 == 0:
        print("  Step {}/{} [OK]  disp = {:.2f} mm  base shear = {:.1f} kN".format(
            i + 1, n_pushover_steps, curr_disp * 1000.0, -base_shear))

print("")
if pushover_ok:
    print("[OK] Pushover analysis complete.")
    print("  Target displacement: {:.1f} mm at Node 3".format(target_disp * 1000))
    print("  Final base shear: {:.1f} kN".format(force_history[-1] if force_history else 0))
else:
    print("[FAIL] Pushover did not complete.")
    if disp_history:
        print("  Last converged disp = {:.2f} mm".format(disp_history[-1]))

# =============================================================================
# Section 6: Results & Visualization  [PostProcessing Agent - Part B]
# =============================================================================

# --- Get nodal displacements BEFORE wipe (model must be alive) ---
node_tags = [1, 2, 3, 4, 5]
disp_dict = {}
for nt in node_tags:
    d = ops.nodeDisp(nt)
    disp_dict[nt] = (d[0], d[1])

# --- Flush recorder buffers by calling wipe ---
ops.wipe()

def safe_loadtxt(path):
    """Load recorder file; return empty array if file missing or empty."""
    try:
        data = np.loadtxt(path)
        if data.ndim == 1:
            data = data.reshape(1, -1)
        return data
    except Exception:
        return np.empty((0, 0))

top_disp_data     = safe_loadtxt('output/top_disp.txt')
midspan_disp_data = safe_loadtxt('output/midspan_disp.txt')
reactions_data    = safe_loadtxt('output/reactions.txt')
fiber_data        = safe_loadtxt('output/fiber_stress.txt')

# --- Extract key results ---
if top_disp_data.size > 0:
    top_disp_series = top_disp_data[:, 1]
    max_top_disp = top_disp_series[-1]
else:
    top_disp_series = np.array([0.0])
    max_top_disp = 0.0

if midspan_disp_data.size > 0:
    midspan_series = midspan_disp_data[:, 1]
    max_midspan_def = abs(midspan_series[-1])
else:
    midspan_series = np.array([0.0])
    max_midspan_def = 0.0

print("=" * 55)
print("  STRUCTURAL ANALYSIS RESULTS SUMMARY")
print("=" * 55)
print("  Max top lateral displacement (Node 3): {:.2f} mm".format(max_top_disp * 1000))
print("  Max mid-span deflection     (Node 5): {:.2f} mm".format(max_midspan_def * 1000))

# --- Equilibrium check (vertical) ---
total_gravity = 10.0 * 6.0  # 10 kN/m x 6 m = 60.0 kN

if reactions_data.size > 0 and reactions_data.shape[1] >= 7:
    fy_node1 = reactions_data[-1, 2]
    fy_node2 = reactions_data[-1, 5]
    reactions_sum_vert = fy_node1 + fy_node2
    residual_vert = abs(reactions_sum_vert - total_gravity)
    equil_status = "[OK]" if residual_vert < 0.01 else "[FAIL]"
    print("")
    print("  Equilibrium check (vertical):")
    print("    Sum Fy reactions : {:.4f} kN".format(reactions_sum_vert))
    print("    Applied gravity  : {:.4f} kN".format(total_gravity))
    print("    Residual         : {:.6f} kN  {}".format(residual_vert, equil_status))
else:
    print("")
    print("  Equilibrium check: reactions data unavailable")

# --- Yielding check ---
fy_steel = 345.0e3   # kPa
ey_steel = fy_steel / 206.0e6

if fiber_data.size > 0 and fiber_data.shape[1] >= 3:
    max_fiber_stress = np.max(np.abs(fiber_data[:, 1]))
    max_fiber_strain = np.max(np.abs(fiber_data[:, 2]))
    yielded = max_fiber_stress >= fy_steel * 0.99
    yield_status = "[YIELDED]" if yielded else "[ELASTIC]"
    print("")
    print("  Column base fiber check (Element 1, section 1):")
    print("    Max fiber stress : {:.2f} MPa  (fy = {:.1f} MPa)".format(
        max_fiber_stress / 1e3, fy_steel / 1e3))
    print("    Max fiber strain : {:.6f}  (ey = {:.6f})".format(
        max_fiber_strain, ey_steel))
    print("    Status           : {}".format(yield_status))
else:
    print("")
    print("  Fiber yielding check: data unavailable")

# --- Deflection check ---
span = 6.0
limit_L250 = span / 250.0
deflection_status = "[OK]" if max_midspan_def <= limit_L250 else "[EXCEEDS LIMIT]"
print("")
print("  Beam deflection check (Node 5):")
print("    Max deflection   : {:.2f} mm".format(max_midspan_def * 1000))
print("    Limit L/250      : {:.2f} mm  (L = {} m)".format(limit_L250 * 1000, span))
print("    Status           : {}".format(deflection_status))
print("=" * 55)


# --- Node coordinates for plots ---
node_coords = {
    1: (0.0, 0.0), 2: (6.0, 0.0),
    3: (0.0, 3.6), 4: (6.0, 3.6), 5: (3.0, 3.6),
}
elements = [(1, 3), (2, 4), (3, 5), (5, 4)]

# --- Plot 1: Frame geometry with loads ---
fig1, ax1 = plt.subplots(figsize=(8, 6))
for (ni, nj) in elements:
    xi, yi = node_coords[ni]
    xj, yj = node_coords[nj]
    ax1.plot([xi, xj], [yi, yj], 'b-', linewidth=2)
for tag, (x, y) in node_coords.items():
    ax1.plot(x, y, 'ko', markersize=6)
    ax1.annotate('N{}'.format(tag), (x, y), textcoords='offset points',
                 xytext=(6, 4), fontsize=9)
for n in SUPPORT_NODES:
    x, y = node_coords[n]
    ax1.plot(x, y, 'k^', markersize=12, markerfacecolor='none', markeredgewidth=2)
# Gravity load arrows
for bx in np.linspace(0.0, 6.0, 7):
    ax1.annotate('', xy=(bx, 3.6), xytext=(bx, 4.2),
                 arrowprops=dict(arrowstyle='->', color='green', lw=1.5))
ax1.plot([0.0, 6.0], [4.2, 4.2], 'g-', linewidth=1.5)
ax1.text(3.0, 4.3, '10 kN/m (gravity)', ha='center', color='green', fontsize=9)
# Lateral load arrow
ax1.annotate('', xy=(0.0, 3.6), xytext=(-1.2, 3.6),
             arrowprops=dict(arrowstyle='->', color='red', lw=2))
ax1.text(-1.3, 3.7, '50 kN', ha='right', color='red', fontsize=9)
ax1.set_xlim(-2.0, 8.0)
ax1.set_ylim(-0.8, 5.0)
ax1.set_aspect('equal')
ax1.set_xlabel('X (m)')
ax1.set_ylabel('Y (m)')
ax1.set_title('Frame Geometry with Applied Loads')
ax1.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.savefig('output/plot_geometry.png', dpi=150)
plt.close(fig1)
print("  Saved: output/plot_geometry.png")

# --- Plot 2: Load-displacement curve with initial stiffness reference ---
fig2, ax2 = plt.subplots(figsize=(8, 5.5))
if len(disp_history) > 0:
    d_arr = np.array(disp_history)
    f_arr = np.array(force_history)

    # Initial elastic stiffness from first few steps
    k0 = f_arr[5] / d_arr[5] if d_arr[5] > 0 else 1.0  # kN/mm

    # Plot actual pushover curve
    ax2.plot(d_arr, f_arr, 'b-', linewidth=2, label='Pushover curve (nonlinear)')

    # Plot initial stiffness line (elastic reference)
    d_ref = np.linspace(0, d_arr[-1], 100)
    ax2.plot(d_ref, k0 * d_ref, 'k--', linewidth=1, alpha=0.6,
             label='Initial stiffness K0 = {:.1f} kN/mm'.format(k0))

    # Shade the gap = nonlinear effect
    f_elastic = k0 * d_arr
    ax2.fill_between(d_arr, f_arr, f_elastic, where=(f_elastic > f_arr),
                     alpha=0.15, color='red', label='Stiffness degradation (nonlinear)')

    # Mark approximate yield point (where curve deviates >5% from elastic)
    for j in range(10, len(d_arr)):
        if f_arr[j] < 0.95 * k0 * d_arr[j]:
            ax2.plot(d_arr[j], f_arr[j], 'r*', markersize=14, zorder=5,
                     label='Yield onset ~ {:.1f} mm'.format(d_arr[j]))
            ax2.axvline(x=d_arr[j], color='r', linestyle=':', alpha=0.4)
            break

    ax2.legend(fontsize=9, loc='lower right')
else:
    ax2.text(0.5, 0.5, 'No data available', transform=ax2.transAxes,
             ha='center', va='center', fontsize=12)
ax2.set_xlabel('Top Lateral Displacement (mm)')
ax2.set_ylabel('Base Shear (kN)')
ax2.set_title('Pushover Curve - Nonlinear Response')
ax2.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.savefig('output/plot_load_disp.png', dpi=150)
plt.close(fig2)
print("  Saved: output/plot_load_disp.png")

# --- Plot 4: Fiber stress-strain curve (direct nonlinearity evidence) ---
fig4, ax4 = plt.subplots(figsize=(8, 5.5))
if fiber_data.size > 0 and fiber_data.shape[1] >= 3:
    strain = fiber_data[:, 2]
    stress_MPa = fiber_data[:, 1] / 1e3   # kPa -> MPa

    ax4.plot(strain * 1000, stress_MPa, 'b-', linewidth=1.5,
             label='Fiber response (y=-0.15, z=0)')

    # Elastic reference line
    E_GPa = 206.0
    strain_ref = np.linspace(min(strain), max(strain), 100)
    stress_elastic = E_GPa * 1000 * strain_ref / 1e3  # GPa -> MPa
    ax4.plot(strain_ref * 1000, stress_elastic, 'k--', linewidth=1, alpha=0.5,
             label='Elastic (E = 206 GPa)')

    # Yield stress lines
    ax4.axhline(y=345, color='r', linestyle=':', alpha=0.6, label='fy = 345 MPa')
    ax4.axhline(y=-345, color='r', linestyle=':', alpha=0.6)

    # Yield strain lines
    ey_val = 345.0 / 206000.0  # = 0.001675
    ax4.axvline(x=ey_val * 1000, color='orange', linestyle=':', alpha=0.5,
                label='ey = {:.3f}'.format(ey_val * 1000))
    ax4.axvline(x=-ey_val * 1000, color='orange', linestyle=':', alpha=0.5)

    ax4.set_xlabel('Strain (x1e-3)')
    ax4.set_ylabel('Stress (MPa)')
    ax4.set_title('Fiber Stress-Strain at Column Base (Element 1, Section 1)')
    ax4.legend(fontsize=9)
    ax4.grid(True, linestyle='--', alpha=0.4)
else:
    ax4.text(0.5, 0.5, 'Fiber data unavailable', transform=ax4.transAxes,
             ha='center', va='center')
plt.tight_layout()
plt.savefig('output/plot_fiber_stress_strain.png', dpi=150)
plt.close(fig4)
print("  Saved: output/plot_fiber_stress_strain.png")

# --- Plot 5: Tangent stiffness degradation ---
fig5, ax5 = plt.subplots(figsize=(8, 5.5))
if len(disp_history) > 10:
    d_arr = np.array(disp_history)
    f_arr = np.array(force_history)

    # Compute tangent stiffness (dF/dd) using central difference
    dd = np.diff(d_arr)
    df = np.diff(f_arr)
    tangent_k = df / dd
    d_mid = (d_arr[:-1] + d_arr[1:]) / 2.0

    # Smooth with moving average (window=15)
    win = 15
    if len(tangent_k) > win:
        kernel = np.ones(win) / win
        tangent_smooth = np.convolve(tangent_k, kernel, mode='valid')
        d_smooth = np.convolve(d_mid, kernel, mode='valid')
    else:
        tangent_smooth = tangent_k
        d_smooth = d_mid

    k0_val = tangent_smooth[0]
    ax5.plot(d_smooth, tangent_smooth, 'b-', linewidth=2, label='Tangent stiffness')
    ax5.axhline(y=k0_val, color='k', linestyle='--', alpha=0.5,
                label='K0 = {:.1f} kN/mm'.format(k0_val))

    # Normalized axis on right
    ax5r = ax5.twinx()
    ax5r.plot(d_smooth, tangent_smooth / k0_val * 100, 'r-', linewidth=0, alpha=0)
    ax5r.set_ylabel('K/K0 (%)', color='gray')
    ax5r.set_ylim(ax5.get_ylim()[0] / k0_val * 100, ax5.get_ylim()[1] / k0_val * 100)

    ax5.set_xlabel('Top Displacement (mm)')
    ax5.set_ylabel('Tangent Stiffness (kN/mm)')
    ax5.set_title('Stiffness Degradation During Pushover')
    ax5.legend(fontsize=9)
    ax5.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.savefig('output/plot_stiffness_degradation.png', dpi=150)
plt.close(fig5)
print("  Saved: output/plot_stiffness_degradation.png")


# --- Plot 3: Deformed shape ---
fig3, ax3 = plt.subplots(figsize=(8, 6))

max_raw_disp = max(
    (disp_dict[nt][0]**2 + disp_dict[nt][1]**2)**0.5
    for nt in node_tags
)
target_visual = 0.36
scale = (target_visual / max_raw_disp) if max_raw_disp > 1e-10 else 1.0

def_coords = {
    nt: (node_coords[nt][0] + scale * disp_dict[nt][0],
         node_coords[nt][1] + scale * disp_dict[nt][1])
    for nt in node_tags
}

# Original shape (dashed grey)
for (ni, nj) in elements:
    xi, yi = node_coords[ni]
    xj, yj = node_coords[nj]
    ax3.plot([xi, xj], [yi, yj], 'k--', linewidth=1, alpha=0.4)

# Deformed shape (solid red)
for idx, (ni, nj) in enumerate(elements):
    xi, yi = def_coords[ni]
    xj, yj = def_coords[nj]
    label = 'Deformed' if idx == 0 else None
    ax3.plot([xi, xj], [yi, yj], 'r-', linewidth=2.5, label=label)

for nt, (x, y) in node_coords.items():
    ax3.plot(x, y, 'k+', markersize=8)
for nt, (x, y) in def_coords.items():
    ax3.plot(x, y, 'ro', markersize=5)
for n in SUPPORT_NODES:
    x, y = node_coords[n]
    ax3.plot(x, y, 'k^', markersize=12, markerfacecolor='none', markeredgewidth=2)

ax3.set_xlim(-1.5, 8.0)
ax3.set_ylim(-0.8, 5.0)
ax3.set_aspect('equal')
ax3.set_xlabel('X (m)')
ax3.set_ylabel('Y (m)')
ax3.set_title('Deformed Shape (scale factor = {:.0f}x)'.format(scale))
ax3.legend(fontsize=9)
ax3.grid(True, linestyle='--', alpha=0.4)

x3d, y3d = def_coords[3]
ax3.annotate('u = {:.1f} mm'.format(max_top_disp * 1000),
             xy=(x3d, y3d), xytext=(x3d + 0.3, y3d + 0.2),
             arrowprops=dict(arrowstyle='->', color='red'),
             color='red', fontsize=9)

plt.tight_layout()
plt.savefig('output/plot_deformed.png', dpi=150)
plt.close(fig3)
print("  Saved: output/plot_deformed.png")
print("  Post-processing complete.")
